services:
  # ----------------------------------------------------------------
  # 1. CORE WAF SERVICES
  # ----------------------------------------------------------------

  go_gateway:
    build: ./gateway
    container_name: go_gateway
    ports:
      - "80:80" # Changed from 8080. Required for Let's Encrypt validation.
      - "443:443" # New. Required for HTTPS.
    depends_on:
      dns_db:
        condition: service_healthy
    environment:
      - MONGO_URI=${MONGO_URI}
      - ML_URL=http://ml_scorer:8000/predict
      - DNS_DB_HOST=dns_db
      - DNS_DB_USER=pdns
      - DNS_DB_PASS=pdns_password
      - DNS_DB_NAME=powerdns
      - FRONTEND_URL=${FRONTEND_URL}
      - WAF_PUBLIC_IP=64.227.156.70 # Add your Droplet IP here
    volumes:
      - certs_volume:/app/certs # Persist SSL certificates so they survive restarts!
    networks:
      - waf_net

  ml_scorer:
    build: ./ml_scorer
    container_name: ml_scorer
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/model.pkl
    networks:
      - waf_net

  dns_db:
    image: mariadb:10.11
    container_name: dns_sql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: powerdns
      MYSQL_USER: pdns
      MYSQL_PASSWORD: pdns_password
    volumes:
      - ./dns/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - dns_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot_password",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - waf_net

  pdns_server:
    image: powerdns/pdns-auth-48:4.8.0
    container_name: pdns_server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8081:8081"
    depends_on:
      dns_db:
        condition: service_healthy
    volumes:
      - ./dns/pdns.conf:/etc/powerdns/pdns.conf
    restart: unless-stopped
    networks:
      - waf_net

  # ----------------------------------------------------------------
  # REMOVED NGINX - The Go Gateway now handles SSL directly
  # ----------------------------------------------------------------

volumes:
  dns_data:
  certs_volume:

networks:
  waf_net:
    driver: bridge
